### ISSUE TITLE
Lots of module installation errors

### ISSUE THREAD

**Issue by fedaykinofdune** [Ruzihm/coin-chance#23]
Having lots of issues trying to install and run with newest nodejs on ubuntu 14.04. Particularly bcrypt fails to build, installed that manually. App.js crashes off the bat, unable to find express-minify. Not sure how drastically things have changed as it's been a while since I've used this, but would a current package.json with updated deps get this going again?

**Comment by Ruzihm** [comment]
Wow! It's been a long time since I've touched this project.

I won't be able to hammer this out until Thursday at the earliest, but
here's how I would begin approaching this:

First, since a suitable version of express-minify can't be found, I would
go into package.json and change the ~ to a ^, which would expand the range
of suitable versions to those sharing the same major version and the same
or greater minor version. In this case, it would expand the range from
[0.0.7, 0.1.0) to [0.0.7, 1.0.0). If the developer of express-minify is
following the versioning conventions properly, the versions in this
expanded range would be compatible with the current code of coin-chance,
and may offer improvements beyond simple bug fixes.

Second, I would consider making that change to each dependency, to avoid
missing any further dependencies. However, I would recommend looking at
each dependency's changelog and seeing if any versions have been deprecated
due to security or other reasons. If a different major version is
recommended, it will likely require a change in some function calls in the
code of coin-chance.

If you want to be bold, you can try these 2 steps and report back. As I
said, the earliest I can get to this is Thursday, but I might not be able
to start, let alone finish, that day.

>

**Comment by fedaykinofdune** [comment]
Thanks for the reply! I'll hopefully have time at some point this weekend to mess with it some more. I really enjoyed using this a while back for a few different coins.

**Comment by fedaykinofdune** [comment]
After lots of trial and error in NPM I've gotten this ironed out. Will submit pull request later.... Still have one more issue though.
